title:                  "Bootstrap"
baseURL:                "https://getbootstrap.com"

docsDir:                "site"

subtitle:               "The most popular HTML, CSS, and JS library in the world."
description:            "Powerful, extensible, and feature-packed frontend toolkit. Build and customize with Sass, utilize prebuilt grid system and components, and bring projects to life with powerful JavaScript plugins."
authors:                "Mark Otto, Jacob Thornton, and Bootstrap contributors"

current_version:        "6.0.0-alpha.1"
current_ruby_version:   "6.0.0-alpha.1"
docs_version:           "6.0"
rfs_version:            "v10.0.0"
github_org:             "https://github.com/twbs"
repo:                   "https://github.com/twbs/bootstrap"
x:                      "getbootstrap"
opencollective:         "https://opencollective.com/bootstrap"
blog:                   "https://blog.getbootstrap.com/"
icons:                  "https://icons.getbootstrap.com/"
examples:               "https://github.com/twbs/examples/tree/main"
swag:                   "https://cottonbureau.com/people/bootstrap"

analytics:
  fathom_site:          "ITUSEYJG"

download:
  source:               "https://github.com/twbs/bootstrap/archive/v6.0.0-alpha.1.zip"
  dist:                 "https://github.com/twbs/bootstrap/releases/download/v6.0.0-alpha.1/bootstrap-6.0.0-alpha.1-dist.zip"
  dist_examples:        "https://github.com/twbs/bootstrap/releases/download/v6.0.0-alpha.1/bootstrap-6.0.0-alpha.1-examples.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:                  "https://cdn.jsdelivr.net/npm/bootstrap@6.0.0-alpha.1/dist/css/bootstrap.min.css"
  css_hash:             "sha384-B/GM4XqrwHnWXNOWMbloTmrYXZg10cakYGmpfsR/bbzQ6JAJI4ihuyADKLnBgrCe"
  js:                   "https://cdn.jsdelivr.net/npm/bootstrap@6.0.0-alpha.1/dist/js/bootstrap.min.js"
  js_hash:              "sha384-BJf/nQgxZJU68GxBse97Vdlc8Rh+z9PzzXiS3/BjV+1nQPR7IKn+iJnD3DJvCMaU"
  js_bundle:            "https://cdn.jsdelivr.net/npm/bootstrap@6.0.0-alpha.1/dist/js/bootstrap.bundle.min.js"
  js_bundle_hash:       "sha384-1a/pXj49ZQ1aHEmrJ+gMw1otqoVsYwlEnlD8mIfY2TV03r20Y0CN7uqx1tQogjPL"
  floating_ui_esm:      "https://cdn.jsdelivr.net/npm/@floating-ui/dom@1.7.6/dist/floating-ui.dom.esm.min.js"
  vanilla_calendar_pro_esm: "https://cdn.jsdelivr.net/npm/vanilla-calendar-pro@3.4.0/index.mjs"

anchors:
  min:                  2
  max:                  5

toc:
  min:                  2
  max:                  3
