window.Modernizr=function(g,e,u){function o(b,a){return typeof b===a}function v(b,a){for(var d in b)if(k[b[d]]!==u)return a=="pfx"?b[d]:!0;return!1}function m(b,a,d){var c=b.charAt(0).toUpperCase()+b.substr(1),e=(b+" "+r.join(c+" ")+c).split(" ");if(o(a,"string")||o(a,"undefined"))a=v(e,a);else{e=(b+" "+w.join(c+" ")+c).split(" ");a:{var b=e,f;for(f in b)if(c=a[b[f]],c!==u){a=d===!1?b[f]:o(c,"function")?c.bind(d||a):c;break a}a=!1}}return a}function H(){f.input=function(b){for(var a=0,d=b.length;a<
d;a++)x[b[a]]=b[a]in h;return x.list&&(x.list=!!e.createElement("datalist")&&!!g.HTMLDataListElement),x}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));f.inputtypes=function(b){for(var a=0,d,c,f,G=b.length;a<G;a++)h.setAttribute("type",c=b[a]),d=h.type!=="text",d&&(h.value=q,h.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(c)&&h.style.WebkitAppearance!==u?(n.appendChild(h),f=e.defaultView,d=f.getComputedStyle&&f.getComputedStyle(h,
null).WebkitAppearance!=="textfield"&&h.offsetHeight!==0,n.removeChild(h)):/^(search|tel)$/.test(c)||(/^(url|email)$/.test(c)?d=h.checkValidity&&h.checkValidity()===!1:/^color$/.test(c)?(n.appendChild(h),d=h.value!=q,n.removeChild(h)):d=h.value!=q)),E[b[a]]=!!d;return E}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var f={},n=e.documentElement,c=e.createElement("modernizr"),k=c.style,h=e.createElement("input"),q=":)",s={}.toString,t=" -webkit- -moz- -o- -ms- ".split(" "),
r="Webkit Moz O ms".split(" "),w="webkit moz o ms".split(" "),c={},E={},x={},z=[],A=z.slice,B,F=function(b,a,d,c){var f,G,I,i=e.createElement("div"),l=e.body,j=l?l:e.createElement("body");if(parseInt(d,10))for(;d--;)I=e.createElement("div"),I.id=c?c[d]:"modernizr"+(d+1),i.appendChild(I);return f=["&#173;<style>",b,"</style>"].join(""),i.id="modernizr",j.innerHTML+=f,j.appendChild(i),l||(j.style.background="",n.appendChild(j)),G=a(i,b),l?i.parentNode.removeChild(i):j.parentNode.removeChild(j),!!G},
C=function(){var b={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(a,d){d=d||e.createElement(b[a]||"div");a="on"+a;var c=a in d;return c||(d.setAttribute||(d=e.createElement("div")),d.setAttribute&&d.removeAttribute&&(d.setAttribute(a,""),c=o(d[a],"function"),o(d[a],"undefined")||(d[a]=u),d.removeAttribute(a))),c}}(),p={}.hasOwnProperty,y;!o(p,"undefined")&&!o(p.call,"undefined")?y=function(b,a){return p.call(b,a)}:y=function(b,a){return a in
b&&o(b.constructor.prototype[a],"undefined")};Function.prototype.bind||(Function.prototype.bind=function(b){var a=this;if(typeof a!="function")throw new TypeError;var d=A.call(arguments,1),c=function(){if(this instanceof c){var e=function(){};e.prototype=a.prototype;var e=new e,f=a.apply(e,d.concat(A.call(arguments)));return Object(f)===f?f:e}return a.apply(b,d.concat(A.call(arguments)))};return c});(function(b,a){var d=b.join(""),c=a.length;F(d,function(a,b){for(var d=e.styleSheets[e.styleSheets.length-
1],d=d?d.cssRules&&d.cssRules[0]?d.cssRules[0].cssText:d.cssText||"":"",i=a.childNodes,l={};c--;)l[i[c].id]=i[c];f.touch="ontouchstart"in g||g.DocumentTouch&&e instanceof DocumentTouch||(l.touch&&l.touch.offsetTop)===9;f.csstransforms3d=(l.csstransforms3d&&l.csstransforms3d.offsetLeft)===9&&l.csstransforms3d.offsetHeight===3;f.generatedcontent=(l.generatedcontent&&l.generatedcontent.offsetHeight)>=1;f.fontface=/src/i.test(d)&&d.indexOf(b.split(" ")[0])===0},c,a)})(['@font-face {font-family:"font";src:url("https://")}',
["@media (",t.join("touch-enabled),("),"modernizr){#touch{top:9px;position:absolute}}"].join(""),["@media (",t.join("transform-3d),("),"modernizr){#csstransforms3d{left:9px;position:absolute;height:3px;}}"].join(""),['#generatedcontent:after{content:"',q,'";visibility:hidden}'].join("")],["fontface","touch","csstransforms3d","generatedcontent"]);c.flexbox=function(){return m("flexOrder")};c.canvas=function(){var b=e.createElement("canvas");return!!b.getContext&&!!b.getContext("2d")};c.canvastext=
function(){return!!f.canvas&&!!o(e.createElement("canvas").getContext("2d").fillText,"function")};c.webgl=function(){try{var b=e.createElement("canvas"),a;a=!(!g.WebGLRenderingContext||!b.getContext("experimental-webgl")&&!b.getContext("webgl"))}catch(d){a=!1}return a};c.touch=function(){return f.touch};c.geolocation=function(){return!!navigator.geolocation};c.postmessage=function(){return!!g.postMessage};c.websqldatabase=function(){return!!g.openDatabase};c.indexedDB=function(){return!!m("indexedDB",
g)};c.hashchange=function(){return C("hashchange",g)&&(e.documentMode===u||e.documentMode>7)};c.history=function(){return!!g.history&&!!history.pushState};c.draganddrop=function(){var b=e.createElement("div");return"draggable"in b||"ondragstart"in b&&"ondrop"in b};c.websockets=function(){for(var b=-1,a=r.length;++b<a;)if(g[r[b]+"WebSocket"])return!0;return"WebSocket"in g};c.rgba=function(){k.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+k.backgroundColor).indexOf("rgba")};c.hsla=function(){k.cssText=
"background-color:hsla(120,40%,100%,.5)";return!!~(""+k.backgroundColor).indexOf("rgba")||!!~(""+k.backgroundColor).indexOf("hsla")};c.multiplebgs=function(){k.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(k.background)};c.backgroundsize=function(){return m("backgroundSize")};c.borderimage=function(){return m("borderImage")};c.borderradius=function(){return m("borderRadius")};c.boxshadow=function(){return m("boxShadow")};c.textshadow=function(){return e.createElement("div").style.textShadow===
""};c.opacity=function(){var b=t.join("opacity:.55;")+"";k.cssText=b;return/^0.55$/.test(k.opacity)};c.cssanimations=function(){return m("animationName")};c.csscolumns=function(){return m("columnCount")};c.cssgradients=function(){var b=("background-image:"+"-webkit- ".split(" ").join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+t.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);k.cssText=b;return!!~(""+k.backgroundImage).indexOf("gradient")};
c.cssreflections=function(){return m("boxReflect")};c.csstransforms=function(){return!!m("transform")};c.csstransforms3d=function(){var b=!!m("perspective");return b&&"webkitPerspective"in n.style&&(b=f.csstransforms3d),b};c.csstransitions=function(){return m("transition")};c.fontface=function(){return f.fontface};c.generatedcontent=function(){return f.generatedcontent};c.video=function(){var b=e.createElement("video"),a=!1;try{if(a=!!b.canPlayType)a=new Boolean(a),a.ogg=b.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,
""),a.h264=b.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),a.webm=b.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(d){}return a};c.audio=function(){var b=e.createElement("audio"),a=!1;try{if(a=!!b.canPlayType)a=new Boolean(a),a.ogg=b.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),a.mp3=b.canPlayType("audio/mpeg;").replace(/^no$/,""),a.wav=b.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),a.m4a=(b.canPlayType("audio/x-m4a;")||b.canPlayType("audio/aac;")).replace(/^no$/,
"")}catch(d){}return a};c.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(b){return!1}};c.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(b){return!1}};c.webworkers=function(){return!!g.Worker};c.applicationcache=function(){return!!g.applicationCache};c.svg=function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg",
"svg").createSVGRect};c.inlinesvg=function(){var b=e.createElement("div");return b.innerHTML="<svg/>",(b.firstChild&&b.firstChild.namespaceURI)=="http://www.w3.org/2000/svg"};c.smil=function(){return!!e.createElementNS&&/SVGAnimate/.test(s.call(e.createElementNS("http://www.w3.org/2000/svg","animate")))};c.svgclippaths=function(){return!!e.createElementNS&&/SVGClipPath/.test(s.call(e.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var D in c)y(c,D)&&(B=D.toLowerCase(),f[B]=c[D](),
z.push((f[B]?"":"no-")+B));f.input||H();f.addTest=function(b,a){if(typeof b=="object")for(var d in b)y(b,d)&&f.addTest(d,b[d]);else{b=b.toLowerCase();if(f[b]!==u)return f;a=typeof a=="function"?a():a;n.className+=" "+(a?"":"no-")+b;f[b]=a}return f};k.cssText="";return c=h=null,function(b,a){function d(){var a=j.elements;return typeof a=="string"?a.split(" "):a}function c(a){var b={},e=a.createElement,f=a.createDocumentFragment,l=f();a.createElement=function(a){var d=(b[a]||(b[a]=e(a))).cloneNode();
return j.shivMethods&&d.canHaveChildren&&!h.test(a)?l.appendChild(d):d};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+d().join().replace(/\w+/g,function(a){return b[a]=e(a),l.createElement(a),'c("'+a+'")'})+");return n}")(j,l)}function e(a){var b;if(!a.documentShived){if(j.shivCSS&&!i){b=a.createElement("p");var d=a.getElementsByTagName("head")[0]||a.documentElement;b=!!(b.innerHTML="x<style>article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}</style>",
d.insertBefore(b.lastChild,d.firstChild))}a=(l||(b=!c(a)),b&&(a.documentShived=b),a)}return a}var f=b.html5||{},h=/^<|^(?:button|form|map|select|textarea)$/i,i,l;(function(){var b=a.createElement("a");b.innerHTML="<xyz></xyz>";i="hidden"in b;l=b.childNodes.length==1||function(){try{a.createElement("a")}catch(b){return!0}var d=a.createDocumentFragment();return typeof d.cloneNode=="undefined"||typeof d.createDocumentFragment=="undefined"||typeof d.createElement=="undefined"}()})();var j={elements:f.elements||
"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:f.shivCSS!==!1,shivMethods:f.shivMethods!==!1,type:"default",shivDocument:e};b.html5=j;e(a)}(this,e),f._version="2.5.3",f._prefixes=t,f._domPrefixes=w,f._cssomPrefixes=r,f.hasEvent=C,f.testProp=function(b){return v([b])},f.testAllProps=m,f.testStyles=F,n.className=n.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+z.join(" ")),f}(this,
this.document);
(function(g,e,u){function o(a){return t.call(a)=="[object Function]"}function v(a){return typeof a=="string"}function m(){}function H(a){return!a||a=="loaded"||a=="complete"||a=="uninitialized"}function f(){var a=r.shift();w=1;a?a.t?q(function(){(a.t=="c"?b.injectCss:b.injectJs)(a.s,0,a.a,a.x,a.e,1)},0):(a(),f()):w=0}function n(a,d,c,h,g,m,i){function l(b){if(!J&&H(j.readyState)&&(o.r=J=1,!w&&f(),j.onload=j.onreadystatechange=null,b)){a!="img"&&q(function(){z.removeChild(j)},50);for(var c in p[d])p[d].hasOwnProperty(c)&&p[d][c].onload()}}
var i=i||b.errorTimeout,j={},J=0,k=0,o={t:c,s:d,e:g,a:m,x:i};p[d]===1&&(k=1,p[d]=[],j=e.createElement(a));a=="object"?j.data=d:(j.src=d,j.type=a);j.width=j.height="0";j.onerror=j.onload=j.onreadystatechange=function(){l.call(this,k)};r.splice(h,0,o);a!="img"&&(k||p[d]===2?(z.insertBefore(j,x?null:s),q(l,i)):p[d].push(j))}function c(a,b,c,e,h){return w=0,b=b||"j",v(a)?n(b=="c"?B:A,a,b,this.i++,c,e,h):(r.splice(this.i++,0,a),r.length==1&&f()),this}function k(){var a=b;return a.loader={load:c,i:0},a}
var h=e.documentElement,q=g.setTimeout,s=e.getElementsByTagName("script")[0],t={}.toString,r=[],w=0,E="MozAppearance"in h.style,x=E&&!!e.createRange().compareNode,z=x?h:s.parentNode,h=g.opera&&t.call(g.opera)=="[object Opera]",h=!!e.attachEvent&&!h,A=E?"object":h?"script":"img",B=h?"script":A,F=Array.isArray||function(a){return t.call(a)=="[object Array]"},C=[],p={},y={timeout:function(a,b){return b.length&&(a.timeout=b[0]),a}},D,b;b=function(a){function d(a){var a=a.split("!"),b=C.length,c=a.pop(),
d=a.length,c={url:c,origUrl:c,prefixes:a},e,f,h;for(f=0;f<d;f++)h=a[f].split("="),(e=y[h.shift()])&&(c=e(c,h));for(f=0;f<b;f++)c=C[f](c);return c}function c(a,b,e,h,i){var g=d(a),m=g.autoCallback;g.url.split(".").pop().split("?").shift();g.bypass||(b&&(b=o(b)?b:b[a]||b[h]||b[a.split("/").pop().split("?")[0]]||f),g.instead?g.instead(a,b,e,h,i):(p[g.url]?g.noexec=!0:p[g.url]=1,e.load(g.url,g.forceCSS||!g.forceJS&&"css"==g.url.split(".").pop().split("?").shift()?"c":u,g.noexec,g.attrs,g.timeout),(o(b)||
o(m))&&e.load(function(){k();b&&b(g.origUrl,i,h);m&&m(g.origUrl,i,h);p[g.url]=2})))}function e(a,b){function d(a,e){if(a)if(v(a))e||(h=function(){var a=[].slice.call(arguments);i.apply(this,a);k()}),c(a,h,b,0,f);else{if(Object(a)===a)for(n in p=function(){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}(),a)a.hasOwnProperty(n)&&(!e&&!--p&&(o(h)?h=function(){var a=[].slice.call(arguments);i.apply(this,a);k()}:h[n]=function(a){return function(){var b=[].slice.call(arguments);a&&a.apply(this,
b);k()}}(i[n])),c(a[n],h,b,n,f))}else!e&&k()}var f=!!a.test,g=a.load||a.both,h=a.callback||m,i=h,k=a.complete||m,p,n;d(f?a.yep:a.nope,!!g);g&&d(g)}var h,g,i=this.yepnope.loader;if(v(a))c(a,0,i,0);else if(F(a))for(h=0;h<a.length;h++)g=a[h],v(g)?c(g,0,i,0):F(g)?b(g):Object(g)===g&&e(g,i);else Object(a)===a&&e(a,i)};b.addPrefix=function(a,b){y[a]=b};b.addFilter=function(a){C.push(a)};b.errorTimeout=1E4;e.readyState==null&&e.addEventListener&&(e.readyState="loading",e.addEventListener("DOMContentLoaded",
D=function(){e.removeEventListener("DOMContentLoaded",D,0);e.readyState="complete"},0));g.yepnope=k();g.yepnope.executeStack=f;g.yepnope.injectJs=function(a,c,g,h,k,n){var i=e.createElement("script"),l,j,h=h||b.errorTimeout;i.src=a;for(j in g)i.setAttribute(j,g[j]);c=n?f:c||m;i.onreadystatechange=i.onload=function(){!l&&H(i.readyState)&&(l=1,c(),i.onload=i.onreadystatechange=null)};q(function(){l||(l=1,c(1))},h);k?i.onload():s.parentNode.insertBefore(i,s)};g.yepnope.injectCss=function(a,b,c,g,h,k){var g=
e.createElement("link"),i,b=k?f:b||m;g.href=a;g.rel="stylesheet";g.type="text/css";for(i in c)g.setAttribute(i,c[i]);h||(s.parentNode.insertBefore(g,s),q(b,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};Modernizr.addTest("placeholder",function(){return"placeholder"in(Modernizr.input||document.createElement("input"))&&"placeholder"in(Modernizr.textarea||document.createElement("textarea"))});
